// <auto-generated />
using System;
using AKZ.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AKZ.API.Data.Migrations
{
    [DbContext(typeof(AKZDbContext))]
    [Migration("20260607051011_AddExportColorPricesTable")]
    partial class AddExportColorPricesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AKZ.API.Models.ExchangeRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ActiveStatus")
                        .HasColumnType("bit");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeleteFlg")
                        .HasColumnType("int");

                    b.Property<string>("FromCurrency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ToCurrency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ExchangeRates");
                });

            modelBuilder.Entity("AKZ.API.Models.Export", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeleteFlg")
                        .HasColumnType("int");

                    b.Property<int?>("ExchangeRateId")
                        .HasColumnType("int");

                    b.Property<decimal>("GrandTotalMMK")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LedgerId")
                        .HasColumnType("int");

                    b.Property<decimal>("ProductAmountCNY")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProductAmountMMK")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SelectedColors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SelectedWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SellingPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SizeSellingPrices")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalExportWeightKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalExportWeightViss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("WorkerFees")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ExchangeRateId");

                    b.HasIndex("LedgerId");

                    b.ToTable("Exports");
                });

            modelBuilder.Entity("AKZ.API.Models.ExportColorPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ExportId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price10")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price10B")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price12")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price14")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price16")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price18")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price20")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price22")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price24")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price26")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price28")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price6")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price7")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price8")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price9")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriceBar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ExportId");

                    b.ToTable("ExportColorPrices");
                });

            modelBuilder.Entity("AKZ.API.Models.Ledger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeleteFlg")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LedgerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Ledgers");
                });

            modelBuilder.Entity("AKZ.API.Models.LedgerMarker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeleteFlg")
                        .HasColumnType("int");

                    b.Property<int>("LedgerId")
                        .HasColumnType("int");

                    b.Property<string>("MarkerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LedgerId");

                    b.HasIndex("ProductId");

                    b.ToTable("LedgerMarkers");
                });

            modelBuilder.Entity("AKZ.API.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeleteFlg")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("AKZ.API.Models.ProcessingRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("ArtificialCount")
                        .HasColumnType("float");

                    b.Property<decimal>("ArtificialWeight")
                        .HasColumnType("decimal(18,4)");

                    b.Property<double>("Count")
                        .HasColumnType("float");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeleteFlg")
                        .HasColumnType("int");

                    b.Property<decimal>("Difference")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("LossWeight")
                        .HasColumnType("decimal(18,4)");

                    b.Property<double>("NaturalCount")
                        .HasColumnType("float");

                    b.Property<double>("NaturalRedCount")
                        .HasColumnType("float");

                    b.Property<decimal>("NaturalRedWeight")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("NaturalWeight")
                        .HasColumnType("decimal(18,4)");

                    b.Property<double>("NaturalWhiteCount")
                        .HasColumnType("float");

                    b.Property<decimal>("NaturalWhiteWeight")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<double>("RedCount")
                        .HasColumnType("float");

                    b.Property<decimal>("RedWeight")
                        .HasColumnType("decimal(18,4)");

                    b.Property<double>("RemArtificialCount")
                        .HasColumnType("float");

                    b.Property<decimal>("RemArtificialWeight")
                        .HasColumnType("decimal(18,4)");

                    b.Property<double>("RemNaturalCount")
                        .HasColumnType("float");

                    b.Property<double>("RemNaturalRedCount")
                        .HasColumnType("float");

                    b.Property<decimal>("RemNaturalRedWeight")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("RemNaturalWeight")
                        .HasColumnType("decimal(18,4)");

                    b.Property<double>("RemNaturalWhiteCount")
                        .HasColumnType("float");

                    b.Property<decimal>("RemNaturalWhiteWeight")
                        .HasColumnType("decimal(18,4)");

                    b.Property<double>("RemRedCount")
                        .HasColumnType("float");

                    b.Property<decimal>("RemRedWeight")
                        .HasColumnType("decimal(18,4)");

                    b.Property<double>("RemShortCount")
                        .HasColumnType("float");

                    b.Property<double>("RemShortCutCount")
                        .HasColumnType("float");

                    b.Property<decimal>("RemShortCutWeight")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("RemShortWeight")
                        .HasColumnType("decimal(18,4)");

                    b.Property<double>("RemSpecialCount")
                        .HasColumnType("float");

                    b.Property<decimal>("RemSpecialWeight")
                        .HasColumnType("decimal(18,4)");

                    b.Property<double>("RemWhiteCount")
                        .HasColumnType("float");

                    b.Property<decimal>("RemWhiteWeight")
                        .HasColumnType("decimal(18,4)");

                    b.Property<double>("RemainingCount")
                        .HasColumnType("float");

                    b.Property<decimal>("RemainingWeight")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("RemainingWeightKg")
                        .HasColumnType("decimal(18,4)");

                    b.Property<double>("ShortCount")
                        .HasColumnType("float");

                    b.Property<double>("ShortCutCount")
                        .HasColumnType("float");

                    b.Property<decimal>("ShortCutWeight")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ShortWeight")
                        .HasColumnType("decimal(18,4)");

                    b.Property<double>("SpecialCount")
                        .HasColumnType("float");

                    b.Property<decimal>("SpecialWeight")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TotalWeight")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("UnitWeight")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("WhiteCount")
                        .HasColumnType("float");

                    b.Property<decimal>("WhiteWeight")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("WorkerNames")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProcessingRecords");
                });

            modelBuilder.Entity("AKZ.API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeleteFlg")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Marker")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Packages")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RemainingWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("WarehouseId")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("AKZ.API.Models.PurificationProcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeleteFlg")
                        .HasColumnType("int");

                    b.Property<bool>("IsWeightFull")
                        .HasColumnType("bit");

                    b.Property<int>("ProcessingRecordId")
                        .HasColumnType("int");

                    b.Property<int?>("PurifierId")
                        .HasColumnType("int");

                    b.Property<double>("PurifyCount")
                        .HasColumnType("float");

                    b.Property<decimal>("PurifyWeight")
                        .HasColumnType("decimal(18,4)");

                    b.Property<double>("RemainingCountAfter")
                        .HasColumnType("float");

                    b.Property<decimal>("RemainingWeightAfter")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProcessingRecordId");

                    b.HasIndex("PurifierId");

                    b.ToTable("PurificationProcesses");
                });

            modelBuilder.Entity("AKZ.API.Models.PurifiedRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Count")
                        .HasColumnType("float");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeleteFlg")
                        .HasColumnType("int");

                    b.Property<bool>("IsWeightFull")
                        .HasColumnType("bit");

                    b.Property<int>("ProcessingRecordId")
                        .HasColumnType("int");

                    b.Property<int?>("PurificationProcessId")
                        .HasColumnType("int");

                    b.Property<int?>("PurifierId")
                        .HasColumnType("int");

                    b.Property<double>("RemainingCount")
                        .HasColumnType("float");

                    b.Property<decimal>("RemainingWeight")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessingRecordId");

                    b.HasIndex("PurificationProcessId");

                    b.HasIndex("PurifierId");

                    b.ToTable("PurifiedRecords");
                });

            modelBuilder.Entity("AKZ.API.Models.Purifier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeleteFlg")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Purifiers");
                });

            modelBuilder.Entity("AKZ.API.Models.RefinementProcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Count")
                        .HasColumnType("float");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeleteFlg")
                        .HasColumnType("int");

                    b.Property<int>("PurifiedRecordId")
                        .HasColumnType("int");

                    b.Property<int?>("RefinementWorkerId")
                        .HasColumnType("int");

                    b.Property<double>("RemainingCountAfter")
                        .HasColumnType("float");

                    b.Property<decimal>("RemainingWeightAfter")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("PurifiedRecordId");

                    b.HasIndex("RefinementWorkerId");

                    b.ToTable("RefinementProcesses");
                });

            modelBuilder.Entity("AKZ.API.Models.RefinementRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Count")
                        .HasColumnType("float");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeleteFlg")
                        .HasColumnType("int");

                    b.Property<decimal>("LostWeight")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("PurifiedRecordId")
                        .HasColumnType("int");

                    b.Property<int?>("RefinementProcessId")
                        .HasColumnType("int");

                    b.Property<int?>("RefinementWorkerId")
                        .HasColumnType("int");

                    b.Property<double>("RemainingCount")
                        .HasColumnType("float");

                    b.Property<decimal>("RemainingWeight")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ReturnWeight")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("SpoilageWeight")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("PurifiedRecordId");

                    b.HasIndex("RefinementProcessId");

                    b.HasIndex("RefinementWorkerId");

                    b.ToTable("RefinementRecords");
                });

            modelBuilder.Entity("AKZ.API.Models.RefinementWorker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeleteFlg")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId");

                    b.ToTable("RefinementWorkers");
                });

            modelBuilder.Entity("AKZ.API.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeleteFlg")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("AKZ.API.Models.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeleteFlg")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("AKZ.API.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeleteFlg")
                        .HasColumnType("int");

                    b.Property<string>("Marker")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PlusMinusWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("SellerId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalRemaining")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SellerId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("AKZ.API.Models.SemiExportRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeleteFlg")
                        .HasColumnType("int");

                    b.Property<int?>("ExchangeRateId")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SingleDoubleDrawnRecordId")
                        .HasColumnType("int");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("WorkerFees")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ExchangeRateId");

                    b.HasIndex("SingleDoubleDrawnRecordId");

                    b.ToTable("SemiExportRecords");
                });

            modelBuilder.Entity("AKZ.API.Models.SingleDoubleDrawnRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeleteFlg")
                        .HasColumnType("int");

                    b.Property<decimal>("LostWeight")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Price10")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Price10B")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Price12")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Price14")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Price16")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Price18")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Price20")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Price22")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Price24")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Price26")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Price28")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Price6")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Price7")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Price8")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Price9")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PriceBar")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PriceReturnSize")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PriceSpoilageSize")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("RefinementRecordId")
                        .HasColumnType("int");

                    b.Property<decimal>("ReturnSize")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ReturnWeight")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("SingleDoubleLostWeight")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Size10")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Size10B")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Size12")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Size14")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Size16")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Size18")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Size20")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Size22")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Size24")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Size26")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Size28")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Size6")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Size7")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Size8")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Size9")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("SizeBar")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("SpoilageSize")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("SpoilageWeight")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("WorkerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RefinementRecordId");

                    b.HasIndex("WorkerId");

                    b.ToTable("SingleDoubleDrawnRecords");
                });

            modelBuilder.Entity("AKZ.API.Models.SingleDoubleDrawnWorker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeleteFlg")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId");

                    b.ToTable("SingleDoubleDrawnWorkers");
                });

            modelBuilder.Entity("AKZ.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeleteFlg")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[DeleteFlg] = 0");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("[DeleteFlg] = 0");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AKZ.API.Models.UserPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeleteFlg")
                        .HasColumnType("int");

                    b.Property<bool>("IsGranted")
                        .HasColumnType("bit");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPermissions");
                });

            modelBuilder.Entity("AKZ.API.Models.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeleteFlg")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("AKZ.API.Models.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeleteFlg")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("AKZ.API.Models.Export", b =>
                {
                    b.HasOne("AKZ.API.Models.ExchangeRate", "ExchangeRate")
                        .WithMany()
                        .HasForeignKey("ExchangeRateId");

                    b.HasOne("AKZ.API.Models.Ledger", "Ledger")
                        .WithMany()
                        .HasForeignKey("LedgerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExchangeRate");

                    b.Navigation("Ledger");
                });

            modelBuilder.Entity("AKZ.API.Models.ExportColorPrice", b =>
                {
                    b.HasOne("AKZ.API.Models.Export", "Export")
                        .WithMany("ColorPrices")
                        .HasForeignKey("ExportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Export");
                });

            modelBuilder.Entity("AKZ.API.Models.LedgerMarker", b =>
                {
                    b.HasOne("AKZ.API.Models.Ledger", "Ledger")
                        .WithMany("Markers")
                        .HasForeignKey("LedgerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AKZ.API.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Ledger");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AKZ.API.Models.ProcessingRecord", b =>
                {
                    b.HasOne("AKZ.API.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AKZ.API.Models.Product", b =>
                {
                    b.HasOne("AKZ.API.Models.Warehouse", "Warehouse")
                        .WithMany("Products")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("AKZ.API.Models.PurificationProcess", b =>
                {
                    b.HasOne("AKZ.API.Models.ProcessingRecord", "ProcessingRecord")
                        .WithMany()
                        .HasForeignKey("ProcessingRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AKZ.API.Models.Purifier", "Purifier")
                        .WithMany()
                        .HasForeignKey("PurifierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ProcessingRecord");

                    b.Navigation("Purifier");
                });

            modelBuilder.Entity("AKZ.API.Models.PurifiedRecord", b =>
                {
                    b.HasOne("AKZ.API.Models.ProcessingRecord", "ProcessingRecord")
                        .WithMany()
                        .HasForeignKey("ProcessingRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AKZ.API.Models.PurificationProcess", "PurificationProcess")
                        .WithMany("PurifiedRecords")
                        .HasForeignKey("PurificationProcessId");

                    b.HasOne("AKZ.API.Models.Purifier", "Purifier")
                        .WithMany()
                        .HasForeignKey("PurifierId");

                    b.Navigation("ProcessingRecord");

                    b.Navigation("PurificationProcess");

                    b.Navigation("Purifier");
                });

            modelBuilder.Entity("AKZ.API.Models.Purifier", b =>
                {
                    b.HasOne("AKZ.API.Models.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("AKZ.API.Models.RefinementProcess", b =>
                {
                    b.HasOne("AKZ.API.Models.PurifiedRecord", "PurifiedRecord")
                        .WithMany()
                        .HasForeignKey("PurifiedRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AKZ.API.Models.RefinementWorker", "RefinementWorker")
                        .WithMany()
                        .HasForeignKey("RefinementWorkerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PurifiedRecord");

                    b.Navigation("RefinementWorker");
                });

            modelBuilder.Entity("AKZ.API.Models.RefinementRecord", b =>
                {
                    b.HasOne("AKZ.API.Models.PurifiedRecord", "PurifiedRecord")
                        .WithMany()
                        .HasForeignKey("PurifiedRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AKZ.API.Models.RefinementProcess", "RefinementProcess")
                        .WithMany("RefinementRecords")
                        .HasForeignKey("RefinementProcessId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AKZ.API.Models.RefinementWorker", "RefinementWorker")
                        .WithMany()
                        .HasForeignKey("RefinementWorkerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PurifiedRecord");

                    b.Navigation("RefinementProcess");

                    b.Navigation("RefinementWorker");
                });

            modelBuilder.Entity("AKZ.API.Models.RefinementWorker", b =>
                {
                    b.HasOne("AKZ.API.Models.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("AKZ.API.Models.RolePermission", b =>
                {
                    b.HasOne("AKZ.API.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AKZ.API.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AKZ.API.Models.Sale", b =>
                {
                    b.HasOne("AKZ.API.Models.Product", "Product")
                        .WithMany("Sales")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AKZ.API.Models.User", "Seller")
                        .WithMany("Sales")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("AKZ.API.Models.SemiExportRecord", b =>
                {
                    b.HasOne("AKZ.API.Models.ExchangeRate", "ExchangeRate")
                        .WithMany()
                        .HasForeignKey("ExchangeRateId");

                    b.HasOne("AKZ.API.Models.SingleDoubleDrawnRecord", "SingleDoubleDrawnRecord")
                        .WithMany()
                        .HasForeignKey("SingleDoubleDrawnRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExchangeRate");

                    b.Navigation("SingleDoubleDrawnRecord");
                });

            modelBuilder.Entity("AKZ.API.Models.SingleDoubleDrawnRecord", b =>
                {
                    b.HasOne("AKZ.API.Models.RefinementRecord", "RefinementRecord")
                        .WithMany()
                        .HasForeignKey("RefinementRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AKZ.API.Models.SingleDoubleDrawnWorker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId");

                    b.Navigation("RefinementRecord");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("AKZ.API.Models.SingleDoubleDrawnWorker", b =>
                {
                    b.HasOne("AKZ.API.Models.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("AKZ.API.Models.User", b =>
                {
                    b.HasOne("AKZ.API.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AKZ.API.Models.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId");

                    b.Navigation("Role");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("AKZ.API.Models.UserPermission", b =>
                {
                    b.HasOne("AKZ.API.Models.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AKZ.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AKZ.API.Models.Export", b =>
                {
                    b.Navigation("ColorPrices");
                });

            modelBuilder.Entity("AKZ.API.Models.Ledger", b =>
                {
                    b.Navigation("Markers");
                });

            modelBuilder.Entity("AKZ.API.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("AKZ.API.Models.Product", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("AKZ.API.Models.PurificationProcess", b =>
                {
                    b.Navigation("PurifiedRecords");
                });

            modelBuilder.Entity("AKZ.API.Models.RefinementProcess", b =>
                {
                    b.Navigation("RefinementRecords");
                });

            modelBuilder.Entity("AKZ.API.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("AKZ.API.Models.User", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("AKZ.API.Models.Warehouse", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
